### ISSUE TITLE
error with DIY deploy from new binder docs

### ISSUE THREAD

**Issue by brooksambrose** [rocker-org/binder#22]
I started a new binderhub deployment following updates from https://github.com/jupyterhub/binderhub/pull/430

Trying to launch example:
http://hub.w201rdada.org/v2/gh/binder-examples/dockerfile-rstudio/master?urlpath=rstudio

At the end of the build log getting:

```Dockerfile
[Warning] One or more build-args [NB_UID NB_USER] were not consumed
Successfully built 171533de9bce
Built image, launching...
Launching server...
Internal Server Error
```

**Comment by brooksambrose** [comment]
this was related to bad config on SSL

**Comment by brooksambrose** [comment]
Still an issue after SSL was disabled.

**Comment by cboettig** [comment]
@brooksambrose is this resolved or should this still be open?

**Comment by brooksambrose** [comment]
Yes solved. The new docs at https://binderhub.readthedocs.io/ are working for me, and for posterity SSL with letsencrypt can be configured as:
```
prefix: gcr.io/<GKE-PROJECT-ID>/binder-prod

jupyterhub:
  proxy:
    https:
      hosts:
        - sub.domain.com
      letsencrypt:
        contactEmail: email@address.com

hub:
  url: https://sub.domain.com
```
